### ISSUE TITLE
Add Kernel-Herding to ADAMS

### ISSUE THREAD

**Issue by csterling** [waikato-datamining/adams-base#10]
Add a transformer to implement kernel-herding algorithm in ADAMS.

@fracpete to advise.

**Comment by fracpete** [comment]
Weka filter (SimpleBatchFilter super class) in adams-weka and adams-weka-lts, spectrum filter in adams-2dim-spectral-core.

**Comment by fracpete** [comment]
Similar to KennardStone classes.
